site_name: "جاده‌ی ابریشم، آنچه باید بدانیم"
site_description: "پروژه‌ای درباره‌ی جاده‌ی ابریشم و تاثیرات آن در تمدن‌های گوناگون"
site_author: Parscasts
repo_url: https://github.com/parscast/silk-road/
site_url: https://parscast.github.io/silk-road/
repo_name: گیت‌هاب این کتاب
edit_uri: edit/main/docs/

theme:
  name: material
  language: fa
  direction: rtl
  font: false
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    # - content.tooltips
    - navigation.expand
    - navigation.sections
#    - navigation.top
    - navigation.footer
    - navigation.instant
#    - navigation.tabs
#    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: تغییر به حالت تیره
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: تغییر به حالت روشن

extra_css:
  - stylesheets/rtl-fix.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css
markdown_extensions:
  - meta
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js
  - javascripts/init-lightbox.js

plugins:
   
#  - search:
#      lang: ['fa', 'en']
nav:
  - درباره‌ی پروژه: about.md
  - مقدمه:
    - پیش‌گفتار: index.md
    - سرزمین و انسان در اوراسیای مرکزی: 00-introduction/ch01-Land-and-man-in-Central-Eurasia.md
    - امپراتوری‌های آسیای داخلی و جاده ابریشم: 00-introduction/ch02-inner-asian-empires-and-the-silk-road.md
    - قلمروهای دینی: 00-introduction/ch03-religious-realms.md
  # - test: test.md
